baseURL = "https://blog-cylg.onrender.com/"
languageCode = "en-us"
title = "Ortexo Blog"
theme = "github-style"

[params]
github = "https://github.com/ortexo"
email = "Hello@ortexo.com"
url = "https://ortexo.com"
keywords = "Blog, saas, npocore, ortexo"


